import ast
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".ipynb_checkpoints",
    "build",
    "dist",
    "node_modules",
    "atlas",
}

STDLIB = set(sys.stdlib_module_names)


def py_files(repo: Path):
    for p in repo.rglob("*.py"):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        yield p


def count_files(repo: Path, pattern: str, subdirs: list[str] | None = None) -> int:
    if subdirs is None:
        return sum(1 for _ in repo.rglob(pattern))

    total = 0
    for subdir in subdirs:
        d = repo / subdir
        if d.exists():
            total += sum(1 for _ in d.rglob(pattern))
    return total


def has_path(repo: Path, path: str) -> bool:
    return (repo / path).exists()


def package_dirs(repo: Path) -> list[Path]:
    return sorted(
        [
            p
            for p in repo.iterdir()
            if p.is_dir()
            and not p.name.startswith(".")
            and p.name not in SKIP_DIRS
            and (p / "__init__.py").exists()
        ],
        key=lambda p: p.name.lower(),
    )


def package_dir_names(repo: Path) -> list[str]:
    return [p.name for p in package_dirs(repo)]


def imports_in_file_split(path: Path) -> tuple[Counter, Counter]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception:
        return Counter(), Counter()

    abs_imports: Counter = Counter()
    rel_imports: Counter = Counter()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            abs_imports.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if not node.module:
                continue
            target = node.module.split(".")[0]
            if node.level:
                rel_imports.update([target])
            else:
                abs_imports.update([target])

    return abs_imports, rel_imports


def repo_imports_split(repo: Path) -> tuple[Counter, Counter]:
    abs_imports: Counter = Counter()
    rel_imports: Counter = Counter()

    for p in py_files(repo):
        a, r = imports_in_file_split(p)
        abs_imports.update(a)
        rel_imports.update(r)

    return abs_imports, rel_imports


def read_version(repo: Path) -> str | None:
    for p in [*(pkg / "__init__.py" for pkg in package_dirs(repo)), repo / "__init__.py"]:
        if not p.exists():
            continue
        for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("__version__"):
                return line.split("=", 1)[1].strip().strip("\"'")
    return None


def read_modidx(repo: Path) -> dict:
    for p in [*(pkg / "_modidx.py" for pkg in package_dirs(repo)), repo / "_modidx.py"]:
        if not p.exists():
            continue

        txt = p.read_text(encoding="utf-8", errors="replace")
        if "Autogenerated by nbdev" not in txt and "'settings'" not in txt:
            continue

        host = re.search(r"""(['"])doc_host\1\s*:\s*(['"])(.+?)\2""", txt)
        baseurl = re.search(r"""(['"])doc_baseurl\1\s*:\s*(['"])(.*?)\2""", txt)

        host_s = host.group(3) if host else None
        baseurl_s = baseurl.group(3) if baseurl else ""

        docs_url = None
        if host_s:
            docs_url = host_s.rstrip("/") + "/" + baseurl_s.lstrip("/")
            docs_url = docs_url.rstrip("/")

        syms_start = txt.find("'syms':")
        if syms_start == -1:
            syms_start = txt.find('"syms":')

        exports_count = txt[syms_start:].count("},") if syms_start > 0 else 0

        return {"nbdev": True, "exports_count": exports_count, "docs_url": docs_url}

    return {"nbdev": False, "exports_count": 0, "docs_url": None}


def read_pyproject_full(repo: Path) -> tuple[str | None, str | None, list, list]:
    pp = repo / "pyproject.toml"
    if not pp.exists():
        return None, None, [], []

    try:
        import tomllib

        data = tomllib.loads(pp.read_text(encoding="utf-8", errors="replace"))
        proj = data.get("project", {})
        return (
            proj.get("name"),
            proj.get("description"),
            proj.get("dependencies", []),
            list(proj.get("scripts", {}).keys()),
        )
    except Exception:
        return None, None, [], []


def importable_names(repo: Path) -> set[str]:
    name, _, _, _ = read_pyproject_full(repo)
    names = {repo.name, repo.name.replace("-", "_").lower()}

    if name:
        names.add(name.replace("-", "_").lower())

    for pkg in package_dirs(repo):
        names.add(pkg.name)

    for p in repo.iterdir():
        if p.is_dir() and (p / "__init__.py").exists():
            names.add(p.name)
        elif p.suffix == ".py" and p.stem not in {"setup"}:
            names.add(p.stem)

    return {n for n in names if n}


def sibling_repos(repo: Path) -> list[Path]:
    parent = repo.parent
    return [
        p
        for p in parent.iterdir()
        if p.is_dir() and not p.name.startswith(".") and p.name not in SKIP_DIRS
    ]


def classify_abs_imports(repo: Path) -> dict[str, Counter]:
    repos = sibling_repos(repo)
    repo_import_names = {r.name: importable_names(r) for r in repos}

    import_to_repos: defaultdict[str, set[str]] = defaultdict(set)
    for rname, names in repo_import_names.items():
        for name in names:
            import_to_repos[name].add(rname)

    abs_imports, rel_imports = repo_imports_split(repo)
    buckets: defaultdict[str, Counter] = defaultdict(Counter)
    self_names = repo_import_names.get(repo.name, {repo.name})

    for mod, n in abs_imports.items():
        if mod in self_names:
            buckets["self"][mod] += n
        elif mod in import_to_repos:
            buckets["sibling"][mod] += n
        elif mod in STDLIB:
            buckets["stdlib"][mod] += n
        else:
            buckets["third_party"][mod] += n

    buckets["relative"] = rel_imports
    return buckets


def repo_card(repo: str | Path, topn: int = 12) -> dict:
    repo = Path(repo).resolve()

    name, desc, deps, scripts = read_pyproject_full(repo)
    version = read_version(repo)
    modidx = read_modidx(repo)
    buckets = classify_abs_imports(repo)

    def fmt(counter: Counter) -> str:
        return ", ".join(f"{k}:{v}" for k, v in counter.most_common(topn))

    readme = repo / "README.md"

    return {
        "repo": repo.name,
        "path": str(repo),
        "project_name": name,
        "description": desc,
        "package_dirs": package_dir_names(repo),
        "version": version,
        "nbdev": modidx["nbdev"],
        "exports_count": modidx["exports_count"],
        "docs_url": modidx["docs_url"],
        "readme_size": len(readme.read_text(encoding="utf-8", errors="replace")) if readme.exists() else 0,
        "py_files": sum(1 for _ in py_files(repo)),
        "nbs_count": count_files(repo, "*.ipynb", ["nbs"]),
        "examples_count": count_files(repo, "*.py", ["examples"]),
        "tests_count": count_files(repo, "*.py", ["tests"]) + count_files(repo, "*.ipynb", ["tests"]),
        "has_llms_txt": (
            has_path(repo, "nbs/llms.txt")
            or has_path(repo, "nbs/llms-ctx.txt")
            or has_path(repo, "nbs/llms-ctx-full.txt")
        ),
        "has_blog": has_path(repo, "nbs/blog"),
        "declared_deps": deps,
        "scripts": scripts,
        "self": fmt(buckets["self"]),
        "sibling": fmt(buckets["sibling"]),
        "third_party": fmt(buckets["third_party"]),
        "stdlib": fmt(buckets["stdlib"]),
        "relative": fmt(buckets["relative"]),
    }


def card_markdown(card: dict) -> str:
    lines = ["# Automated Card", "", "```json", json.dumps(card, indent=2, default=str), "```", ""]
    return "\n".join(lines)